# docker-compose.yml
version: "3.8"
services:
  app:
    build: .
    ports:
      - "5040:5080"
    environment:
      - NODE_ENV=production
      - NGROK_AUTHTOKEN=2rAyishYgHRna2NmoIBY0e9YSfS_5eRm536CBFtvp6onX5Cef
      - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
      - VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
      - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
      - VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
      - VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
      - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
      - VITE_FIREBASE_MEASUREMENT_ID=${VITE_FIREBASE_MEASUREMENT_ID}
      - VITE_API=${VITE_API}
    env_file:
      - .env

    # Optional: Add volume mounts if you need hot reloading during development
    # volumes:
    #   - .:/app
    #   - /app/node_modules
